// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /mnt/d/yamanami_keyboard/cherry_mx/icon/logo_and_text.png --output /home/s-show/qmk_firmware/keyboards/yamanami_cherry --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_logo_and_text_length;
extern const uint8_t  gfx_logo_and_text[101];
